### PR TITLE
Webpack setup

### PR DESCRIPTION
**Pull request by richpeters**
Supports ES6 and reactJS. Currently set up so local dev setup uses `webpack-dev-server` and serves files from memory, whereas production setup creates bundles in `static/dist` directory for Django `staticfile` requirements

### CODE REVIEW

**Comment by tomkins** [comment]
Anna/Edvinas, have a play around with this and see what you think.

It doesn't have to be perfect right now - we'll give it a good test on this project before it goes into the django-template repo.

**Comment by arh30** [comment]
Looks really good to me, great gulping and v clean base.html. Sass structure and partials are separately logically, great work 👍🤩

**Comment by zatan** [comment]
1. It doesn't work throws the errors on the server npm I am using is v8.9.4
```
> @ serve /var/www/commonslibrary
> node server.js

events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 127.0.0.1:8080
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at Server.setupListenHandle [as _listen2] (net.js:1351:14)
    at listenInCluster (net.js:1392:12)
    at doListen (net.js:1501:7)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:686:11)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ serve: `node server.js`
npm ERR! Exit status 1
npm ERR! 

```
2. Files like server.js and postcss.js or something should be sitting in seperate directory not in root.

**Comment by zatan** [comment]
Spoke with rich sorted all the things and requested few changes.

**Pull request merged**
