### PR TITLE
Replace and style The Campaigns Library header text

### PR DESCRIPTION
**Pull request by MichelleGreensted**
# Sources
https://trello.com/c/guqW3oIB/23-can-we-please-have-the-words-the-campaigns-library-written-across-the-top-of-page

# Description
This PR replaces the original 'Hello there' header text with the text 'The Campaigns Library' and adds styling similar to the design inspiration provided. 

# How to test
Go to http://127.0.0.1:8000/ and check that the next 'The Campaigns Library' header text looks right in terms of text and styling. I have made the border and alignment as similar to the inspiration screenshot as possible, but as there is no subheader to break the border and the colour palette is different I've gone with some of my own initiative of what looks good here. Please let me know if you have any suggestions!

For comprehensive guidelines on code review at DEV, see here: https://www.notion.so/developersociety/Code-Review-f804361f9b6b4859bdcd69d7704168e5.

# Pre-review checklist
- [x] PR Tags & Milestones?
- [x] Are any general setup instructions added to the README?
- [x] Have you updated the docs/changelog.md (if required)?
- [x] Have you updated the docs/features.md (if required)?

### CODE REVIEW

**Review by HayleyK2019 — APPROVED** [review]
Think that's fine? They asked a lot of things in that card, and also mentioned something about a grey background for one of the banners? 

Possibly this bit?
Screenshot 2023-06-23 at 15 36 55

**Review by HayleyK2019 — CHANGES_REQUESTED** [review]
Actually I think they want to remove the "Todays featured resources" too?>

"instead of the Hello There! and the today's featured resources, - we have 'The Campaigns Library" across that bit?"

**Comment by MichelleGreensted** [comment]
@HayleyK2019 

> Think that's fine? They asked a lot of things in that card, and also mentioned something about a grey background for one of the banners?
> 
> Possibly this bit? Screenshot 2023-06-23 at 15 36 55

Good catch thank you, I've added the grey to the banner.

**Comment by MichelleGreensted** [comment]
> Actually I think they want to remove the "Todays featured resources" too?>
> 
> "instead of the Hello There! and the today's featured resources, - we have 'The Campaigns Library" across that bit?"

I see what you mean but going by [this card](https://trello.com/c/USkvFjDT/24-2-can-we-move-the-type-to-search-resources-to-above-the-latest-so-it-will-now-go-directly-under-the-new-the-campaigns-library-po) I think they probably do what to keep the featured resources?

**Comment by MichelleGreensted** [comment]
> > Actually I think they want to remove the "Todays featured resources" too?>
> > "instead of the Hello There! and the today's featured resources, - we have 'The Campaigns Library" across that bit?"
> 
> I see what you mean but going by [this card](https://trello.com/c/USkvFjDT/24-2-can-we-move-the-type-to-search-resources-to-above-the-latest-so-it-will-now-go-directly-under-the-new-the-campaigns-library-po) I think they probably do what to keep the featured resources, just have it further down on the page?

Realised this is about the Today's featured resource in the top right so have added changes to remove that from the page

**Comment by MichelleGreensted** [comment]
Happy for someone else to merge this if the new requested changes are approved

**Review by HayleyK2019 — APPROVED** [review]

**Pull request merged**
